name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With parameters '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what should have happened!
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - macOS 12 (Monterey)
        - macOS 13 (Ventura)
        - macOS 14 (Sonoma)
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - Other Linux distribution
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: shell
    attributes:
      label: Shell
      description: What shell are you using?
      options:
        - PowerShell 5.1
        - PowerShell 7.x
        - Bash
        - Zsh
        - Fish
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: nodejs-version
    attributes:
      label: Node.js version
      description: What version of Node.js are you using?
      placeholder: e.g., 18.17.0
    validations:
      required: true

  - type: input
    id: npm-version
    attributes:
      label: npm version
      description: What version of npm are you using?
      placeholder: e.g., 9.6.7
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error output or screenshots
      description: If applicable, add screenshots or copy-paste the error output to help explain your problem.
      placeholder: Paste your error output here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
